spring: 
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: Levy1987
    
    jpa:
    show-sql: true
    hibernate:
    ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
